prebid/prebid-cache

backends/decorators/metrics.go
backends/decorators/metrics_test.go
endpoints/decorators/metrics.go
endpoints/decorators/metrics_test.go
endpoints/get.go
endpoints/integration_test.go
endpoints/put.go
main.go
metrics/metricstest/assertions.go

When making the project open-source, the URL changed. This fixes the imports so that it builds smoothly again.

Fixed the imports

---

backends/aerospike.go

If the aerospike cluster is misconfigured, the client here will return `nil, nil`. This causes the app to crash on `rec.Bins["value"].(string)`
This makes it a bit more robust, and should make read times more efficient too (if, for example, the same namespace was used for multi-bin values in other apps)

Fixed a small bug in the aerospike client

---

backends/decorators/size_limit.go
backends/decorators/size_limit_test.go
endpoints/integration_test.go
endpoints/put.go
main.go

Followup from #20.
This addresses two issues:
- Payload size limits are enforced _after_ compression
- Size metrics are taken for _all_ payloads (even those which are rejected for size)

More payload metrics

---

README.md
config/config.go
config/config_test.go

This makes Prebid Cache respect environment variables, like `PBC_PORT` or `PBC_COMPRESSION_TYPE`.
Basically the PBC analogue to https://github.com/prebid/prebid-server/pull/407.

Respect environment variables

---

config/backends.go
config/config.go
main.go

To make it very explicit which configuration values the app is running, unless they pose security risks (e.g. `password`).
Output on startup looks like this:
```
dbemiller-mac:prebid-cache dbemiller$ ./prebid-cache 
INFO[0000] config.port: 2424                            
INFO[0000] config.admin_port: 2525                      
INFO[0000] config.log.level: info                       
INFO[0000] config.rate_limiter.enabled: true            
INFO[0000] config.rate_limiter.num_requests: 100        
INFO[0000] config.request_limits.max_size_bytes: 10240  
INFO[0000] config.request_limits.max_num_values: 10     
INFO[0000] config.backend.type: memory                  
INFO[0000] config.compression.type: snappy              
INFO[0000] config.metrics.type: none                    
INFO[0000] …
```

Log config values on startup

---

backends/config/config.go
config/config.go

We had a bug related to this in Prebid Server... and I stumbled on this while doing other stuff. Figured I'd remove it before we hit the same issue here.

Removed explicit viper.Get() calls

---

backends/config/config.go

See the code comment for rationale... if that doesn't explain it, let me know and I'll try to make it more clear.
Only real reason I'm doing the quick fix here is because I want to test some new deployment scripts today, and if we're gonna release on a Friday, we should do it early.

Swapped the order on metrics/compression.

---

backends/aerospike.go
backends/config/config.go
backends/decorators/metrics.go
backends/decorators/metrics_test.go
metrics/core.go

Adding metrics to tell:
- How many objects define TTLs through the API
- How much longer an object would have remained in the cache, for Aerospike
Goal here is to help PBS hosts tune the configurable Default TTLs.

Added aerospike expiry metrics

---

config/config.go
endpoints/get.go
endpoints/integration_test.go
endpoints/routing/handler.go

Tested this full circuit locally, so this should be the final PR.

Allows fetching custom non-UUID keys when support is enabled

---

backends/memory.go

Using the memory backend can cause panics if we have two request writing at exactly the same time.

Concurrent map usage is not safe

---

backends/azure_table.go
endpoints/put.go

Putting whole objects in a pool only works if you put in pointers. Otherwise the interface{} conversion is still going to cause an allocation.
See: https://play.golang.org/p/dDoWFnuf9bb
When you put a slice in a pool you also need to put in a pointer to the slice.
See: https://play.golang.org/p/yitACT4RLDY

Fix proper sync.Pool usage

---

config.yaml
config/config.go
config/config_test.go
endpoints/index.go
endpoints/routing/handler.go
main.go
server/server.go
server/server_test.go

We intend on using prebid-cache to cache responses from a backend, and hand out the urls to the cache for the frontend clients to consume. prebid-cache currently exposes both the POST and the GET for cache items to the public API, which is not ideal if we never want the public to be able to write to our cache.
This change:
- Adds configuration `routes.allow_public_write` to disable writes on the public port (2424 default)
- Adds a read/write not rate limited handler into the API for the admin port (2525 default)
- Adds configuration `routes.index_response` to change the messaging on the `/` response
Related to https://github.com/prebid/prebid-cache/issues/36 which is asking for this functionality.
Tested it locally with the various flags on/off using CURL and it seems to work fine, …

Add configuration for admin only POST, default route message changing

---

README.md

This PR modifies `README.md` to explain how to disable the rate limiter if needed. Rate limiter is enabled by default.

Document rate limiter configuration 

---

backends/aerospike.go
backends/aerospike_test.go
backends/errors.go
endpoints/integration_test.go

Prebid Cache is able use of a number of back-end systems. We rather not identify the back-end system (Aerospike, Redis, Cassandra or Azure) in the error messages whenever they come up. This pull request removes the "Aerospike" string from any error message the Aerospike back-end may throw.

Remove "Aerospike" string from Aerospike backend error messages

---

backends/config/config.go

The config option `request_limits.max_size_bytes` caps the maximum size of the `request.puts[i].value` fields but if Prebid Cache was configured to compress data (`config.compression.type` set to `snappy`) elements bigger than `request_limits.max_size_bytes` may still pass validation because they get compressed before getting checked.
This pull request corrects the aforementioned bug by swapping the order in which the decorators get assigned to wrap the data store backend.

Correct payload size limit

---

endpoints/get_test.go
utils/errors.go
utils/errors_test.go

Eventually we may want to correct the error messages but for the moment let's roll back the capitalization of the first letter of the `MISSING_KEY` type error messages.

Rolledback uppercase in MISSING_KEY type errors

---

endpoints/put.go
endpoints/put_test.go

`parsePutObject()` returns an error, but those error messages were getting ignored because we were not exiting the  `put(...)` function immediately after the error check.

Bug fix. Displaying wrong error messages

---

README.md
backends/aerospike.go
backends/aerospike_test.go
go.mod
go.sum

This pull request updates the Aerospike Go client to the latest version `v6.2.1` requires Aerospike server version 4.9+ and will not work properly with older versions. Full documentation of the Aerospike Go client can be found [here](https://github.com/aerospike/aerospike-client-go/tree/v6).

Update to Aerospike Client version v6.2.1

---

config/config.go
config/config_test.go
metrics/prometheus/prometheus.go

Resolves issue #114, thanks @pgodzin. This pull request addesses the feature gap between Prebid Server and Prebid Cache in regards to allowing prometheus namespace and subsystem to be empty, as opposed to erroring out as before:
```
func (promMetricsConfig *PrometheusMetrics) validateAndLog() {
-     // validate
if promMetricsConfig.Port == 0 {
log.Fatalf(`Despite being enabled, prometheus metrics came with an empty port number: config.metrics.prometheus.port = 0`)
}
-     if promMetricsConfig.Namespace == "" {
-         log.Fatalf(`Despite being enabled, prometheus metrics came with an empty name space: config.metrics.prometheus.namespace = %s.`, promMetricsConfig.Namespace)
-     }
-     if promMetricsConfig.Subsystem == "" {
-         log.Fatalf(`Despite being enabled, prometheus …
```

Allow prometheus namespace and subsystem to be empty

---

backends/aerospike.go
config/backends.go
config/backends_test.go

When instantiated, the Aerospike client defaults to 2 retries per read operation and 0 retries for a write operation. This pull request makes this values configurable.

Aerospike: Make write and read max retries configurable

---

config/config.go
config/config_test.go

Forgot to set Max write and read retry default values so Viper reads the environment variable version of them

Set default values for max_write_retries and max_read_retries

---

go.mod
go.sum

Aerospike Go client [v6.4.0](https://github.com/aerospike/aerospike-client-go/releases/tag/v6.4.0) fixes major bugs related to connections
```
We recommend you update to this version ASAP. A bug might occur when a client performing a scan hits a "Partition
Unavailable" during an unstable cluster (in both high availability (AP) and strong consistency (CP) modes). Previous versions
of the client aborted the scan and put the connection back into the pool, which might cause unprocessed results to be sent
to a different transaction (of the same client), possibly resulting in incorrect application behavior. This has been fixed by Go
Client v5.10.0 and v6.4.0.
```

Update Aerospike client version to 6.7.0

---

backends/aerospike.go
config/backends.go
config/backends_test.go
config/config.go

By default the Aerospike client starts with a connection queue cache size of 256 per node. This pull request implements `ConnQueueSize` that lets the host set this value from the configuration file or an environment variable.
**yaml**
```yaml
backend:
type: "memory" # Can also be "aerospike", "cassandra", "memcache" or "redis"
aerospike:
host: "aerospike.prebid.com"
port: 3000
namespace: "whatever"
connection_queue_size: 64
```
**json**
```json
{
"port": 2424,
"admin_port": 2525,
"log": {
"level": "info"
},
"backend": {
"type": "aerospike",
"aerospike": {
"host": "aerospike.prebid.com",
"port": 3000,
"namespace": "whatever",
"connection_queue_size": 64
}
}
}
```
**Environment variable**
```bash
PBC_BACKEND_TYPE="aerospike"
PBC_BACKEND_AEROSPIKE_HOST="aerospike.prebid.com" …
```

Make Aerospike client connection queue size configurable

---

.github/workflows/cross-repo-issue.yml

This is the process change we've been discussing, having github automatically open an issue in one repo when a PR is merged to its twin. Starting with PBC as a test, the idea would be to put versions of this workflow script in all 4 PBS/PBC repos
Conditions:
- merge close (not cancel close)
- label is not "do not port"
Here's a screenshot of what a resulting issue in PBC-Java would look like:
Obviously, you'll want to mentally replace "test1" with "PBC-Go" for this diagram.

Workflow to create issue in pbc-java

---

config.yaml

When configuring the Aerospike backend, `config.backend.aerospike.host` is being deprecated in favor of `config.backend.aerospike.hosts`, an array of URLs. This pull requests tweaks the default configuration file `config.yaml` to encourage the use of `config.backend.aerospike.hosts` over `config.backend.aerospike.host`.
Created as an answer to the concern raised in issue #128

Push for the use of "aerospike.hosts" in config file

---

.github/workflows/validate-merge.yml
.github/workflows/validate.yml
Dockerfile

Ubuntu 18.04 is reaching End of Standard Support in May 2023. This pull request updates Github actions files and the Dockerfile to make use of the next Long Term Support (LTS) release: Ubuntu 20.04

Update to Ubuntu 20.04

---

.github/workflows/validate-merge.yml
.github/workflows/validate.yml

Github has ended support for node 12 and has recommended plugin maintainers to use node 16 before summer 2023. Refer [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) for more details. Public repos like [prebid server](https://github.com/prebid/prebid-server) and [prebid cache](https://github.com/prebid/prebid-cache) make use of community plugins in actions. As part of this PR, we are updating actions to use newer version of plugin which has support for node 16.

Update actions to use newer version to support node.js 16

---

.github/workflows/cross-repo-issue.yml
.github/workflows/issue_prioritization.yml

Github has ended support for node 12 and has recommended plugin maintainers to use node 16 before summer 2023. Refer [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) for more details. Public repos like [prebid server](https://github.com/prebid/prebid-server) and [prebid cache](https://github.com/prebid/prebid-cache) make use of community plugins in actions. As part of this PR, we are updating actions to use newer version of plugin which has support for node 16.

Update tibdex/github-app-token version to support node.js16

---

.github/workflows/release.yml

- Release workflow yml uses docker/login-action v1. This version runs on node 12. 
- Github actions has announce to deprecate node 12 and has recommended to use node 16 (https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12). 
- Latest version of docker/login-action runs on node 16. Therefore use latest version of docker/login-action.
- Testing: Similar changes are done for prebid-server repo. Details are [here](https://github.com/prebid/prebid-server/pull/2769#issue-1705482205).

Update docker/login-action version

---

backends/aerospike.go
backends/aerospike_test.go
backends/config/config_test.go

Issue #162 documents a `NewAerospikeBackend` unit test that fails. When looking into the issue documented in issue #162 the need to refactor `NewAerospikeBackend`, for more accurate testing and better readability, was evident. This pull request makes such modifications.

Refactor NewAerospikeBackend function

---

go.mod
go.sum

This PR bumps google.golang.org/protobuf from 1.28.0 to 1.33.0 and substitutes #171

Update google.golang.org/protobuf from 1.28.0 to 1.33.0

---

go.mod
go.sum

The update is to fix the dependabot issue triggered by the `github.com/rs/cors` version prior to `v1.11.0`.  I wonder why the dependabot didn't pick it and didn't propose an autoupdate PR in this repository - do you know, by any chance?
> Middleware causes a prohibitive amount of heap allocations when processing malicious preflight requests that include an Access-Control-Request-Headers (ACRH) header whose value contains many commas. This behavior can be abused by attackers to produce undue load on the middleware/server as an attempt to cause a denial of service.
References: https://github.com/rs/cors/issues/145, https://github.com/rs/cors/pull/173

update github.com/rs/cors to v1.11.0
